### PR TITLE
assignment_08_12

### PR DESCRIPTION
**Pull request by luodongchen**

### CODE REVIEW

**Comment by Lozu** [comment]
Notes:
1. While I can register and then log in, it seems that test@te.st/1234 credentials do not work (when I type them in login screen nothing happens. Please add this special case.
2. When I log in, I see the screen with "go to Fragment A" button. When I click on it I get transferred to login screen. I suppose it should change FragmentB to FragmentA instead.
3. On unsuccessful logins or registration I see no error indications. Nothing happens. Please change this.
4. Remove template garbage like "companion object" and param1/param2 from FragmentB and LoginFragment files.
5. In FragmentB you have comment with something on Chinese. Please refrain from writing comments on language other than English, because it can not be reviewed. 
6. In your xml files put strings and common attributes into strings.xml and styles.xml files.

**Comment by luodongchen** [comment]
1234 is not a valid strong enough password,so it won't br registered, On unsuccessful logins or registration, there are label report , i will try to fix the rest

**Comment by Lozu** [comment]
Was there such requirement to have strong passwords? I remember that we must handle test@te.st with 1234 password in any case.

**Comment by luodongchen** [comment]
build will collapse when i try to remove those template stuff

**Comment by Lozu** [comment]
Are you sure? Will it collapse if you just remove "companion object"s?

**Comment by luodongchen** [comment]
when it doesn't disturb the function, we can ee it for now, too much to rewrite when i remove those things

**Comment by Lozu** [comment]
You just have to remove ~20 lines in each file, but okay. This is up to you.

**Comment by luodongchen** [comment]
ok,thanks!

**Pull request merged**
